cockroachdb/apd

- bench_test.go
- context.go
Hi Matt,
The Ln code looks good to me! I just have this suggested minor improvement to replace `Mul` by `decimalTwo` with an `Add` (should be a bit faster). I couldn't run the benchmark to verify if we see an improvement though.
I think we could stop the loop when the delta (tmp2) becomes small enough (less than `10^-c.Precision` or so). We would also optimize out the `Sub` in `loop.done()` since we already know the delta. I will look at that.
By the way, I don't quite understand the logic in `loop.done()`; we "stall" when `l.delta.Cmp(l.prevDelta) == 0`? Why? I would expect in most iterative algorithms the delta to keep decreasing.. So we should stop when it becomes 0 or smaller than a certain value no?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> ln: minor improvements

- context.go
- loop.go
Note: only the last commit is the subject of this PR (the others are in a separate one).
The loop termination criteria was very funky. I have fixed it in the repo we
got this code from: robpike/ivy#32
Applying a similar (but better) fix here. When doing iterations, we want the
"inner" computations to be done at a higher precision. But the iteration should
stop when the estimate reaches the desired "outer" precision. This desired
precision is now passed to newLoop.
An alternative would be to use the precision in the context. This would mean
that iterations would use an "inner" context and an "outer" (loop) context. I
figured this could be more confusing/error-prone.
```
Ln/P2/S-100/D2-24       973µs ± 1%   645µs ± 2%  -33.76%  (p=0.029 n=4+4)
Ln/P2/S-10/D2-24        472µs ± 2%   321µs ± 2% …
```
> better loop termination criteria

- context.go
- decimal.go
- gda_test.go
- round.go
- table.go
- table_test.go
```
name                 old time/op  new time/op  delta
GDA/abs-12           91.5µs ± 1%  98.9µs ±21%     ~     (p=0.690 n=5+5)
GDA/add-12           6.35ms ± 9%  4.77ms ±11%  -24.85%  (p=0.008 n=5+5)
GDA/base-12          1.05ms ± 7%  1.03ms ± 7%     ~     (p=0.151 n=5+5)
GDA/compare-12        552µs ± 4%   515µs ± 1%   -6.70%  (p=0.008 n=5+5)
GDA/divide-12        1.64ms ±11%  1.45ms ± 9%  -11.78%  (p=0.032 n=5+5)
GDA/divideint-12      254µs ± 8%   184µs ± 7%  -27.36%  (p=0.008 n=5+5)
GDA/exp-12            177ms ±13%   107ms ±12%  -39.57%  (p=0.008 n=5+5)
GDA/ln-12             405ms ±24%   353ms ±41%     ~     (p=0.098 n=13+15)
GDA/log10-12          561ms ±16%   302ms ± 3%  -46.16%  (p=0.008 n=5+5)
GDA/minus-12          142µs ±21%    97µs ± 1%  -31.64%  (p=0.008 n=5+5)
GDA/multiply-12 …
```
> use a table for 10^x calculations

- decimal.go
```
name          old time/op  new time/op  delta
GDA/reduce-4   215µs ±30%   124µs ±10%  -42.48%  (p=0.008 n=5+5)
```
Idea from: https://github.com/cockroachdb/cockroach/blob/0ba52ff84a3e67efe3532b9119058aab8231478a/pkg/util/encoding/decimal.go#L773
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/apd/20)
> use uint64 in reduce when possible

- table.go
- table_test.go
Also don't take Abs when not needed.
```
name                old time/op    new time/op    delta
NumDigitsLookup-12     775µs ±14%     381µs ± 3%  -50.80%  (p=0.008 n=5+5)
NumDigitsFull-12      13.0ms ±19%    12.8ms ±11%     ~     (p=1.000 n=5+5)
name                old alloc/op   new alloc/op   delta
NumDigitsLookup-12     115kB ± 0%      22kB ± 0%     ~     (p=0.079 n=4+5)
NumDigitsFull-12      4.49MB ± 0%    3.91MB ± 0%  -12.88%  (p=0.008 n=5+5)
name                old allocs/op  new allocs/op  delta
NumDigitsLookup-12     2.14k ± 0%     0.42k ± 0%  -80.43%  (p=0.008 n=5+5)
NumDigitsFull-12       34.6k ± 0%     31.1k ± 0%  -10.06%  (p=0.008 n=5+5)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> NumDigits: minor speedups in lookup table logic

- context.go
- table.go
Nothing used the guaranteed setting of the 2nd param, remove.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/apd/23)
> simplify returns for exp10 funcs

- bench_test.go
- const.go
- decimal.go
- decimal_test.go
Can avoid an allocation by the caller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/apd/25)
> Add SetString to Context

- context.go
- round.go
When rounding from -0.9 to -1.0, the coefficient would be first set
to 0, and then 1 added to it. Since 0 isn't negative, 1 was added
instead of subtracted as it should have been. The fix is to record
the sign before rounding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/apd/27)
> round: fix rounding bug found by quantize

- context.go
- decimal_test.go
- error.go
- gda_test.go
Not sure how we passed the GDA tests before, but the first test case
added in TestQuantize was failing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/apd/26)
> quantize: correct results when rounding

- context.go
- gda_test.go
Power calculations of x**y where y is an integer will now correctly
be flagged as exact when possible. This avoids lots of work and is
thus much faster for these operations.
Remove some unneeded precision changing in integerPower. It
was leftover from the inf code which did bad things with 1/x
calculations. This was causing some overflow problems that shouldn't
have been present.
This change reduces `go test` time from 2.5s to 0.9s.
```
name          old time/op  new time/op  delta
GDA/power-12   666ms ±16%   387ms ± 6%  -41.86%  (p=0.008 n=5+5)
```
---
First commit is from another PR, but has a fix this needs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/apd/30)
> pow: correctly compute exactness

- context.go
Neither of the branches that modified approx here were taken in any
tests, so the tests still pass without them. Even though this is
described in the paper, I think it is safe to remove.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/apd/43)
> Remove unused block in sqrt

- context.go
- decimal.go
- decimal_test.go
- error.go
- gda_test.go
This is useful to determine if any zero truncation occurred without running a CmpTotal.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/apd/46)
> return number of zeros removed during reduce

- decimal.go
- decimal_test.go
Moving the exponent next to the flag so they share the same word. This decreases
the size of `Decimal` by 8 bytes (to 48). Adding a test that needs to be updated
if the size changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/apd/52)
> reduce the size of the Decimal struct

- context.go
- decimal_test.go
Similar to the previous commit, reduces Context from 40 to 32.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/apd/53)
> reduce the size of the Context struct

- const.go
C3 was incorrectly using the C2 constant. Luckily this was only used
for the initial approximation, and thus affected only performance,
not correctness.
> use correct cbrt estimation const

- context.go
- decimal.go
- decimal_test.go
This behavior is explicitly tested for in GDA, but the implementation was
only in the Context struct. Move it to the Decimal struct so that any
users of Decimal will benefit from this, as it is standard across int,
float, and decimal specifications.
> Prevent decimal.Neg from returning -0

- example_test.go
Import paths need to include a "/v2" in them if referencing a version greater then v1.
> apd: update example to use apd/v2

- decomposer.go
- decomposer_test.go
This implements the interface as worked on in the
issue https://golang.org/issue/30870 .
> apd: add decomposer interface methods

- decimal.go
This was preventing a few uses of `apd.Decimal` from being stack-allocated in CRDB code.
> apd: prevent (*Decimal).Int64 receiver from escaping to heap

- .github/workflows/go.yml
- README.md
- bigint.go
- bigint_go1.14_test.go
- bigint_go1.15.go
- bigint_go1.15_test.go
- bigint_test.go
- const.go
- context.go
- decimal.go
- decimal_test.go
- error.go
- example_test.go
- gda_test.go
- go.mod
- loop.go
- round.go
- table.go
- table_test.go
Fourth time's the charm.
Replaces cockroachdb/cockroach#74369.
Replaces https://github.com/cockroachdb/apd/pull/101.
Replaces https://github.com/cockroachdb/apd/pull/102.
This is an alternative to #102. At a high-level, it implements the "compact memory representation" described in https://github.com/cockroachdb/apd/pull/102#issuecomment-1005078022. Compared to the approach in that PR, this approach is a) [faster for most operations](https://github.com/cockroachdb/apd/pull/102#issuecomment-1005970829), b) more usable because values can be safely copied, c) half the memory size (32 bytes per `Decimal`, vs. 64).
The memory representation of the Decimal struct in this approach looks like:
```go
type Decimal struct {
Form     int8
Negative bool
Exponent int32
Coeff    BigInt {
_inner …
```
> apd: embed small coefficient values in Decimal struct

- bigint.go
- bigint_test.go
This commit adds a `MathBigInt` and a `SetMathBigInt` method to `BigInt`.
These allow the type to more easily interoperate with `math/big.Int`.
> apd: add apd.BigInt / math/big.Int interop methods

- bigint.go
- context.go
- decimal.go
- round.go
This PR contains a series of follow-on micro-optimizations that build upon the changes in https://github.com/cockroachdb/apd/pull/106.
The individual changes here focus primarily on inlining function calls on the hot paths and on manually unrolling loops where possible. For the first form of optimization, it uses `gcassert` to detect regressions. I'm still hoping to add `gcassert` to CI, but that is currently blocked on https://github.com/jordanlewis/gcassert/pull/3.
Impact on benchmark suite:
```
name                 old time/op    new time/op    delta
GDA/squareroot-10      16.0ms ± 1%    12.6ms ± 0%  -21.26%  (p=0.000 n=8+9)
GDA/abs-10             6.14µs ± 1%    4.85µs ± 0%  -21.04%  (p=0.000 n=10+8)
GDA/powersqrt-10        246ms ± 0%     195ms ± 1%  -20.49%  (p=0.000 n=9+9) …
```
> apd: tune performance by inlining function calls and manually unrolling loops

- .github/workflows/go.yml
- bigint.go
This commit adds `gcassert:noescape` directives to `bigint.go` to verify
that the temporary big.Int values that are intended to be stack-allocated
do not escape to the heap.
The commit then adds `gcassert` to CI.
> apd: use gcassert to check that tmp big.Ints don't escape, add to CI

- bigint.go
- context.go
- round.go
- table.go
This PR includes a pair of minor optimizations that avoid function calls on arithmetic hot paths.
This commit adds a fast-path for the common case in `Context.goError` that avoids the function call to `Condition.GoError`. `Context.goError` is inlined in callers, so this avoids any function call in the common case.
This commit reworks the call to `Context.round` to allow for mid-stack function inlining. To do this, we remove the conditional call to one of two functions, which is considered too complex to inline.
----
```
name                 old time/op    new time/op    delta
GDA/minus-10           6.43µs ± 5%    6.11µs ± 5%  -5.11%  (p=0.000 n=25+25)
GDA/subtract-10        85.3µs ± 5%    81.2µs ± 2%  -4.81%  (p=0.000 n=25+19)
GDA/abs-10             4.76µs ± 5%    4.58µs ± 6%  -3.87% …
```
> apd: avoid function calls on hot paths

- .github/workflows/go.yml
See https://github.com/dominikh/go-tools/issues/1251.
> apd: disable staticcheck on Go 1.16 and earlier

- .github/workflows/go.yml
This commit adds a test variant for go 1.18.
> apd: add go 1.18 testing to CI

- decimal.go
exps contains exactly 0, 1, or 2 elements.
Provide space for 2 elements up front.
This is an easy, broadly positive optimization.
Some of the time/op benchmarks are noisy;
the allocs benchmarks are clearer.
```
name                           old time/op    new time/op    delta
Exp/P5/S-4/D-2-8                  823ns ± 2%     917ns ±23%  +11.34%  (p=0.000 n=19+19)
Exp/P5/S-4/D2-8                   894ns ±18%     876ns ±15%     ~     (p=0.141 n=18+18)
Exp/P5/S-1/D-2-8                 1.60µs ± 1%    1.73µs ±26%   +8.07%  (p=0.000 n=20+19)
Exp/P5/S-1/D2-8                  1.77µs ± 1%    1.96µs ±21%  +11.08%  (p=0.000 n=20+19)
Exp/P5/S2/D-2-8                  3.92µs ± 1%    4.07µs ±10%   +3.93%  (p=0.049 n=20+17)
Exp/P5/S2/D2-8                   4.38µs ± 0%    4.44µs ± 2%   +1.42%  (p=0.000 …
```
> apd: remove some allocs from Decimal.setString

- bigint.go
Not important, but easy enough to do and makes a difference for the
performance of `Decimal.setString`, which #116 was interested in.
> apd: add inline fast-path to BigInt.SetString

- condition.go
- context.go
- decimal.go
- go.mod
- go.sum
- loop.go
- sql_test.go
Fixes https://github.com/cockroachdb/apd/issues/123.
Now that the stdlib's "errors" package supports wrapping, use it to eliminate a dependency on "github.com/pkg/errors".
Picks up the "lib/pq" test dependency. Bump `go.mod` to `go 1.17` to allow users of the library to prune this dependency (https://go.dev/ref/mod#graph-pruning).
@mvdan do you mind giving this a look?
> apd: drop github.com/pkg/errors

- bench_test.go
- format.go
Prefer to use Append and allocate scratch space
to improve speed and efficiency of string conversion:
```
name              old time/op    new time/op    delta
DecimalString-10     147ns ± 1%      56ns ± 4%  -62.14%  (p=0.000
n=10+10)
name              old alloc/op   new alloc/op   delta
DecimalString-10     84.0B ± 0%     39.0B ± 0%  -53.57%  (p=0.000
n=10+10)
name              old allocs/op  new allocs/op  delta
DecimalString-10      5.00 ± 0%      1.00 ± 0%  -80.00%  (p=0.000
n=10+10)
```
> apd: Improve string conversion efficiency

- .github/workflows/go.yml
- gda_test.go
This commit adds a test variant for go 1.19.
> apd: add go 1.19 testing to CI

- .github/workflows/go.yml
This commit adds a test variant for go 1.20.
> apd: add go 1.20 testing to CI

- .github/workflows/go.yml
This commit adds a test variant for go 1.21 and 1.22.
> apd: add go 1.21 and 1.22 testing to CI

- .github/workflows/go.yml
- bigint_go1.15_test.go
- decimal_test.go
Fixes #138.
The test was failing due to https://github.com/golang/go/commit/6dfd7a543517db868ef4f31e91fe56aba5bc8ea0. This PR fixes it.
This PR then adds a test variant for go 1.23.
> apd: fix TestFormatFlags on go 1.23, add go 1.23 to CI
